### ISSUE TITLE
Allow user to change email

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#106]
Currently the updateAccount endpoint only allows to alter first name, last name and whether the user is a representative. We also need the provide the possibility to change the email address and maybe even the username.

**Comment by codingfabi** [comment]
@redfrexx can you give an update on this?
If implemented please provide link to the endpoint documentation :)

**Comment by redfrexx** [comment]
According to the [django-graphql-auth docs](https://django-graphql-auth.readthedocs.io/en/latest/api/) the only way to change the email would be. 

1. Add a secondary email for the user using [`sendSecondaryEmailActivation` mutation](https://django-graphql-auth.readthedocs.io/en/latest/api/#sendsecondaryemailactivation)
2. User receives confirmation email with token, which the user submits via our website (same as registration). Password is needed additionally though, since it is needed by the following requests.
3. Verify secondary email using [`verifySecondaryEmail` mutation](https://django-graphql-auth.readthedocs.io/en/latest/api/#verifysecondaryemail)
4. Swap the primary and secondary emails using [`swapEmails` mutation](https://django-graphql-auth.readthedocs.io/en/latest/api/#swapemails)
5. Remove the old email which is now the secondary email using [`removeSecondaryEmail`](https://django-graphql-auth.readthedocs.io/en/latest/api/#removesecondaryemail).

Steps 3, 4 and 5 can be combined in one request though. 

``` graphql 
    mutation ($token: String!, $password: String!){
      verifySecondaryEmail(
        token: $token
      ) {
        success, errors
      }
      swapEmails(
        password: $password
      ) {
        success,
        errors
      }
      removeSecondaryEmail(
        password: $password
      ) {
        success,
        errors
      }
    }
```

Would that work from the frontend perspective?

**Comment by redfrexx** [comment]
We decided to remove the username in #145

**Comment by sami1riaz** [comment]
I signed out of an account and was able to go back to this page: 
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/22355825/186801086-8662399d-d616-434d-9fde-68a403759511.png">
