### ISSUE TITLE
Page for planning a commuting/business trip

### ISSUE THREAD

**Issue by codingfabi** [pledge4future/WePledge#155]
To plan a business trip the users want to compare the emissions of different transportation modes. 
We should create a page that allows them to create an altered version of a commuting trip and a business trip where users provide the distance or start and end adress and can submit these stats and get a presentation of the results. 

We need to do the following: 

- [ ] create a page with an altered business trip form in one tab and an altered commuting form in another tab 
- [ ] connect the page to the new comparison endpoint specified in #152 
- [ ] Add results of the comparison on the same page or navigate him to the results details page specified in #154

**Comment by alexbercik** [comment]
Just following up from the discussion today where this was discussed; I think at some point this should connect with the capability for multimodal/multicity trips. We would need a way to account for layovers between cities (etc. train, plane), since the distances can change dramatically and potentially the emission factors as well when one moves from one country to another. We should keep this in mind and discuss it at a future date.
