### ISSUE TITLE
Disable some features for deployment on pledge4future.org

### ISSUE THREAD

**Issue by redfrexx** [pledge4future/WePledge#194]
For deployment on pledge4future.org we need to disable some features for now:
- [x] Log in
- [x] Emission planner 

@codingfabi, you had an idea of how to do this in the frontend

**Comment by codingfabi** [comment]
There are two approaches to do this: 

1. The simpler way would be to use next.js environment variables ([see this documentation](https://nextjs.org/docs/basic-features/environment-variables#loading-environment-variables)) and then host two versions, one with a test config and one with a production config. We could then select features that are only available with a production flag. On the downside, this is a bit hacky to implement as it would require an access to the environment variable in basically every frontend file (I am not sure if we could just remove the routes for prod deployment).

2. There are packages that allow a more sophisticated approach and lets us configure features for singular users, e.g. [this one](https://github.com/happykit/flags). The problem is that this would be a bit overkill I think as this would require a finished user concept and as we want to disable the features for all users anyway, I am not sure if we should use this.

I would propose to implement the approach 1. and see how far we can get with it... thoughts @sami1riaz @redfrexx ?

**Comment by codingfabi** [comment]
I implemented approach 1 in https://github.com/pledge4future/WePledge/pull/198

This still yields the problem that users can access the disabled routes directly via the url. I will try to find a solution for this in the upcoming days.
